# Generated by Django 5.2.5 on 2025-09-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
