# Generated by Django 4.2.1 on 2025-09-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='linkedin_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
