# Generated by Django 4.2.1 on 2025-09-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_linkedin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
    ]
