# Generated by Django 4.2.1 on 2025-09-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_company_address_company_telephone'),
        ('leads', '0004_lead_job_title'),
    ]

    operations = [
    ]
