# Generated by Django 4.2.1 on 2025-09-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_merge_20250919_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(default='78572632-9ace-430e-840e-7fe86e5d4651', on_delete=django.db.models.deletion.PROTECT, related_name='lead_company', to='leads.company'),
        ),
    ]
