# Generated by Django 4.2.1 on 2025-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_merge_20250919_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=255, verbose_name='Company'),
        ),
    ]
