# Generated by Django 4.2.1 on 2025-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company'),
        ),
    ]
