# Generated by Django 4.2.1 on 2025-09-26 13:30

from django.db import migrations


def populate_company_field(apps, schema_editor):
    Lead = apps.get_model('leads', 'Lead')
    # Update all leads with NULL company field to have a default value
    Lead.objects.filter(company__isnull=True).update(company='Unknown Company')


def reverse_populate_company_field(apps, schema_editor):
    # This is a no-op for reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_company'),
    ]

    operations = [
        migrations.RunPython(populate_company_field, reverse_populate_company_field),
    ]
