# Generated by Django 4.2.1 on 2025-09-26 13:32

from django.db import migrations, models


def populate_company_values(apps, schema_editor):
    Lead = apps.get_model('leads', 'Lead')
    # Update all leads with NULL or empty company field to have a default value
    Lead.objects.filter(company__isnull=True).update(company='Unknown Company')
    Lead.objects.filter(company='').update(company='Unknown Company')


def reverse_populate_company_values(apps, schema_editor):
    # This is a no-op for reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20250926_1530'),
    ]

    operations = [
        migrations.RunPython(populate_company_values, reverse_populate_company_values),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(max_length=255, null=False, blank=False, verbose_name='Company'),
        ),
    ]
