# Generated by Django 4.2.1 on 2025-09-26 13:34

from django.db import migrations


def verify_company_field(apps, schema_editor):
    """
    Verify that all company fields have valid values.
    This migration ensures data integrity for team members.
    """
    Lead = apps.get_model('leads', 'Lead')
    
    # Count leads with NULL or empty company values
    null_count = Lead.objects.filter(company__isnull=True).count()
    empty_count = Lead.objects.filter(company='').count()
    
    if null_count > 0 or empty_count > 0:
        # Update any remaining NULL or empty values
        Lead.objects.filter(company__isnull=True).update(company='Unknown Company')
        Lead.objects.filter(company='').update(company='Unknown Company')
        print(f"Updated {null_count + empty_count} leads with missing company values")


def reverse_verify_company_field(apps, schema_editor):
    # This is a no-op for reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20250926_1532'),
    ]

    operations = [
        migrations.RunPython(verify_company_field, reverse_verify_company_field),
    ]
