# Generated by Django 4.2.1 on 2025-09-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20250926_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('referrals', 'Referrals & Recommendations'), ('marketing', 'Digital Content & SEO'), ('advertisement', 'Paid Ads (Google, LinkedIn, Meta)'), ('networking', 'Networking & Professional Platforms'), ('events', 'Events & Trade Shows'), ('campaign', 'Email/Call Campaigns'), ('other', 'Other')], max_length=255, null=True, verbose_name='Source of Lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('assigned', 'Assigned'), ('in_process', 'In Process'), ('converted', 'Converted'), ('recycled', 'Recycled'), ('closed', 'Closed')], max_length=255, null=True, verbose_name='Status of Lead'),
        ),
    ]
