# Generated by Django 4.2.1 on 2025-10-01 11:00

from django.db import migrations, models, connection
import django.db.models.deletion


def make_company_nullable(apps, schema_editor):
    """
    Make company_id column nullable
    """
    with connection.cursor() as cursor:
        cursor.execute("ALTER TABLE lead ALTER COLUMN company_id DROP NOT NULL")


def reverse_make_company_nullable(apps, schema_editor):
    """
    Reverse migration - make company_id NOT NULL
    """
    with connection.cursor() as cursor:
        # First, set any NULL values to a default company
        cursor.execute("""
            UPDATE lead 
            SET company_id = (SELECT id FROM company WHERE name = 'Unknown Company' LIMIT 1)
            WHERE company_id IS NULL
        """)
        # Then make it NOT NULL
        cursor.execute("ALTER TABLE lead ALTER COLUMN company_id SET NOT NULL")


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_lead_company'),
    ]

    operations = [
        migrations.RunPython(make_company_nullable, reverse_make_company_nullable),
    ]
