# Generated by Django 4.2.1 on 2025-10-01 11:01

from django.db import migrations, connection


def remove_unknown_company(apps, schema_editor):
    """
    Remove the 'Unknown Company' from the database and set leads to NULL
    """
    with connection.cursor() as cursor:
        # First, set all leads with 'Unknown Company' to NULL
        cursor.execute("""
            UPDATE lead 
            SET company_id = NULL 
            WHERE company_id = (SELECT id FROM company WHERE name = 'Unknown Company')
        """)
        
        # Then delete the 'Unknown Company' record
        cursor.execute("DELETE FROM company WHERE name = 'Unknown Company'")


def reverse_remove_unknown_company(apps, schema_editor):
    """
    Reverse migration - recreate 'Unknown Company' and assign it to leads with NULL company
    """
    with connection.cursor() as cursor:
        # Create 'Unknown Company' again
        cursor.execute("""
            INSERT INTO company (id, name, address, telephone, created_at, updated_at, org_id)
            SELECT gen_random_uuid(), 'Unknown Company', '', '', NOW(), NOW(), NULL
            WHERE NOT EXISTS (SELECT 1 FROM company WHERE name = 'Unknown Company')
        """)
        
        # Get the 'Unknown Company' ID
        cursor.execute("SELECT id FROM company WHERE name = 'Unknown Company'")
        result = cursor.fetchone()
        if result:
            unknown_company_id = result[0]
            
            # Update leads with NULL company to use 'Unknown Company'
            cursor.execute("""
                UPDATE lead 
                SET company_id = %s 
                WHERE company_id IS NULL
            """, [unknown_company_id])


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_make_company_nullable'),
    ]

    operations = [
        migrations.RunPython(remove_unknown_company, reverse_remove_unknown_company),
    ]
