# Generated by Django 4.2.1 on 2025-09-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_userinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
