# Generated by Django 4.2.1 on 2025-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_alter_profile_alternate_phone_alter_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SALES', 'Sales'), ('SALES_MANAGER', 'Sales Manager'), ('MARKETING', 'Marketing'), ('MARKETING_MANAGER', 'Marketing Manager'), ('SUPPORT', 'Support')], default='USER', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SALES', 'Sales'), ('SALES_MANAGER', 'Sales Manager'), ('MARKETING', 'Marketing'), ('MARKETING_MANAGER', 'Marketing Manager'), ('SUPPORT', 'Support')], default='USER', max_length=50),
        ),
    ]
