# Generated by Django 4.2.1 on 2025-09-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_roles_alter_profile_role_alter_userinvitation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('SALES', 'Sales'), ('SALES_MANAGER', 'Sales Manager'), ('MARKETING', 'Marketing'), ('MARKETING_MANAGER', 'Marketing Manager'), ('SUPPORT', 'Support')], default='SALES', max_length=50),
        ),
    ]
